name: Deploy Python Flask App to Azure Web App - finbuddy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3️⃣ Install dependencies locally for optional validation
      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pip install flake8
        # This step ensures your requirements.txt is valid
        # and dependencies are installable before deploying

      # # 4️⃣ Run optional local checks (like lint or tests)
      - name: Check syntax and simple errors
        run: flake8 . || true


      # 5️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'finbuddy'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B17C3DD47C3547EAA0B4DDA123B20802 }}
          package: .



